# Site settings
title: Organ Quality Assessment
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://organ-quality-assessment.github.io/orqa-website/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Organ Quality Assessment
user_description: Developing software to objectively "score" the quality of organs being considered for transplant.
user_title: Software Engineer
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: murraco
# github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

